_target_: datasets.SingleCellDataset
h5ad_dir: data/mouse/datasets/cellXGene
description_dir: data/mouse/descriptions
obs_cols: 
  - final_annotation
  - lineage
  - tag
  - assay_ontology_term_id
  - cell_type_ontology_term_id
  - development_stage_ontology_term_id
  - donor_id
  - disease_ontology_term_id
  - is_primary_data
  - organism_ontology_term_id
  - self_reported_ethnicity_ontology_term_id
  - sex_ontology_term_id
  - suspension_type
  - tissue_type
  - tissue_ontology_term_id
  - cell_type
  - assay
  - disease
  - organism
  - sex
  - tissue
  - self_reported_ethnicity
  - development_stage
  - observation_joinid