defaults:
  - _self_
  - dataset: preprocessed_cell_x_gene
  - metadata: single_cell
  - prompt: cell_whisper_single_cell
  - llm: openai
  - model: mouseformer

exp:
  run_func: 
    _target_: experiment.train_clip

  seed: 42
  log_dir: # set during runtime to automatically created dir
  
  # Genomics encoder config
  cell_vocab_size: 57000
  max_cell_tokens: 1200
  cell_embed_dim: 512
  cell_transformer_heads: 8
  cell_transformer_layers: 4
  
  # Text encoder config
  text_model_name: "google-bert/bert-base-cased"
  max_text_tokens: 128
  text_proj_dim: 256
  
  # Projection config
  projection_dim: 256
  dropout: 0.1
  
  # Training config
  batch_size: 128
  epochs: 10
  lr: 5e-5
  min_lr: 1e-6
  weight_decay: 0.01
  num_workers: 64
  model_save_path: "best_genomics_clip.pt"
  use_wandb: true
  log_accuracy: true

wandb:
  project: sc-rna
  entity: tml-uw
  tags: []