defaults:
  - _self_
  - dataset: sc_compass
  - metadata: single_cell
  - prompt: cell_whisper_single_cell
  - llm: openai
  - model: mouseformer

exp:
  run_func: 
    _target_: experiment.extract_text_annotation

  seed: 42
  log_dir: # set during runtime to automatically created dir
  
  model: gpt-4o-mini # o1-mini 
  temperature: 0.7
  top_k_genes: 10

  batch_size: 1

  output_path: data/generated/mouse/generated/single_cell.csv

  file_id: ???

wandb:
  project: sc-rna
  entity:
  tags: