_target_: langchain_core.prompts.ChatPromptTemplate
_convert_: object
messages:
  - _target_: langchain_core.prompts.chat.HumanMessagePromptTemplate.from_template
    template: |
      Human: You are a biomedical researcher. Your task is to extract the biologically relevant information from a sample's metadata indicated by <<<>>> and representing them in natural language.

      # Instructions

      ## Represent Biological Information
      Only consider information that are reflective of the sample's biology: phenotype, transcriptome, genotype, cell type and condition or treatments.

      ## Study-Level Information
      This is just additional context and should not be included in the response, beyond informing about the the nature of the sample.

      ## Ignore Non-Biological Information
      Ignore information that is not relevant to the cellular state of the sample. Specifically, exclude all IDs and details about technical and methodological processes such as sequencing type, read length, platform, or any other laboratory technique-related information.

      ## Focus on specific cell details
      If top K most expressed genes are provided, focus on the genes that are most relevant to the cellular state of the sample and its biological interpretation.

      ## Response Template
      Respond in two parts following the JSON template below.
      {
          "1. Relevant Information to be Included": <List[str]: List of information to be extracted, according to the instructions above>,
          "2. Final Response": <str: brief natural language description of the sample focusing solely on the biological aspects that contribute to understanding its cellular state>,
      }

      ## Diveristy of text responses
      Please provide diverse responses that are not identical to the provided metadata and different from each other.
      Your previous response was: 
      The sample consists of endothelial cells derived from the bone marrow of C57BL/6 mice, specifically progenitor cells that are viable and express markers CD45+ and CD127+, while being lineage-negative. The genotype indicates that these cells are from animals with a knocked-out LCR1 gene.

      # Provided Metadata

      <<<
      {query}

      Top K most expressed genes in the sample:
      {top_k_genes}
      >>>
